### ISSUE TITLE
Github action fails "Setup ruby" when using Gemfile from README.md

### ISSUE THREAD

**Issue by bschonec** [voxpupuli/gha-puppet#27]
I created a completely blank puppet module, copied over Gemfile and Rakefile verbatim, created the puppet.yml Github action file and upon creating a pull request, the Github action [fails at "Setup Ruby"](https://github.com/bschonec/bschonec-spec_testing/actions/runs/4206954295/jobs/7301111694
).  I believe this is because the Gemfile doesn't have a pointer to get the gems installed.  I added the following to the top of the Gemfile:

`source ENV['GEM_SOURCE'] || 'https://rubygems.org'
`
re-ran the action and the "Setup Ruby" job passed.

The Gemfile at [voxpupuli/puppet-chrony](https://github.com/voxpupuli/puppet-chrony/blob/master/Gemfile#L4) implies that the GEM_SOURCE needs to be set.

**Comment by ekohl** [comment]
Yes, you're right. It must be set. Would you be willing to submit a PR to `README.md` so you get proper credit?

**Comment by bschonec** [comment]
Resolved by #28
