### ISSUE TITLE
Find a convention for specifying Puppet's version to Gemfile

### ISSUE THREAD

**Issue by ekohl** [voxpupuli/gha-puppet#3]
Vox Pupuli uses https://github.com/voxpupuli/modulesync_config/blob/a87ca50493f5b1ac09956fd7f8c226cf6fc3165f/moduleroot/Gemfile.erb#L38-L39 or:
```ruby
puppetversion = ENV['PUPPET_VERSION'] || '<%= @configs['puppet_version'] %>'
gem 'puppet', puppetversion, :require => false, :groups => [:test]
```

The Foreman uses puppetversion = ENV['PUPPET_VERSION'] || '<%= @configs['puppet_version'] %>'
gem 'puppet', puppetversion, :require => false, :groups => [:test] or:
```ruby
gem 'puppet', ENV.key?('PUPPET_VERSION') ? "~> #{ENV['PUPPET_VERSION']}" : '>= 5.5', groups: ['development', 'test']
```

pdk-templates uses https://github.com/puppetlabs/pdk-templates/blob/b851eaa1db21ee695c07da1a9594a86403bfcc18/moduleroot/Gemfile.erb#L103-L109 or (summarized for readability):
```ruby
def location_for(place_or_version, fake_version = nil)
  git_url_regex = %r{\A(?<url>(https?|git)[:@][^#]*)(#(?<branch>.*))?}
  file_url_regex = %r{\Afile:\/\/(?<path>.*)}

  if place_or_version && (git_url = place_or_version.match(git_url_regex))
    [fake_version, { git: git_url[:url], branch: git_url[:branch], require: false }].compact
  elsif place_or_version && (file_url = place_or_version.match(file_url_regex))
    ['>= 0', { path: File.expand_path(file_url[:path]), require: false }]
  else
    [place_or_version, { require: false }]
  end
end

puppet_version = ENV['PUPPET_GEM_VERSION']
gem_params = location_for(puppet_version)
gem 'puppet', *gem_params
```

So none of these really is the same:
* VP and Foreman use `PUPPET_VERSION` as the environment variable but PDK uses `PUPPET_GEM_VERSION`
* VP and PDK use the full specifier while Foreman forces `~>`

If these workflows are to be used by all, it would be good to align on a single convention.

`PUPPET_GEM_VERSION` does have the benefit that it doesn't overlap with `PUPPET_VERSION` which is also used in beaker-puppet_install_helper (https://github.com/puppetlabs/beaker-puppet_install_helper/blob/41c355b1f83fde562dd5bd6961e2e4eb8b81421c/lib/beaker/puppet_install_helper.rb#L128) which, while archived, is still used by Vox Pupuli and Foreman in their Beaker setups.

**Comment by bastelfreak** [comment]
do you have preference here? My first feelings are we should switch to PUPPET_GEM_VERSION to avoid the overlap. I think for VP we sometimes set the matchet (`>=`, `~>` as well, but foreman only sets the actual version only?

**Comment by ekohl** [comment]
I didn't want to push my own idea too much, but I'm also leaning to `PUPPET_GEM_VERSION`. And I'm ok with including the matcher in Foreman. I rarely if ever change it in my local environment and for CI it's trivial to change.

**Comment by bastelfreak** [comment]
using `PUPPET_GEM_VERSION` sounds good to me.
